---
title: JS异步面试题目
date: 2021-08-31 14:19:34
permalink: /pages/05105e/
categories:
  - 更多
  - 面试
tags:
  -
---

## Promise 的三种状态，如何变化

- 三种状态是: pending resolved rejected
- 变化: pending ---> resolved ---> rejected
- 并且他们的变化是不可逆的

## 场景题 - promise then 和 catch 的连接

```js
// 第一题

Promise.resolve()
  .then(() => {
    console.log(1)
  })
  .catch(() => {
    console.log(2)
  })
  .then(() => {
    console.log(3)
  })

// 1 3
```

- 因为 Promise.resolve.then 可以执行，打印 1。
- 然后.then 的返回结果是 resolved 状态的 Promise,所以 catch 不会执行，2 不会被打印。
- 然后执行下面的这个.then，打印 3。所以打印结果为 `1, 3`。

```js
// 第二题
Promise.resolve()
  .then(() => {
    console.log(1)
    throw new Error('error1')
  })
  .catch(() => {
    console.log(2)
  })
  .then(() => {
    console.log(3)
  })

// 1 2 3
```

- 因为 Promise.resolve.then 可以执行，打印 1,之后立马抛了个错误'error'。
- 抛错误之后.then 返回的是 reject 状态的 Promise,所以执行 catch,打印 2。
- 执行完.cath 整个返回的是 resolve 状态的 Promise,所以.then 会执行，然后打印 3。
- 打印结果为：`1,2,3`。

```js
Promise.resolve()
  .then(() => {
    console.log(1)
    throw new Error('error1')
  })
  .catch(() => {
    console.log(2)
  })
  .catch(() => {
    console.log(3)
  })

// 1 2
```

- 因为 Promise.resolve.then 可以执行，打印 1,之后立马抛了个错误'error'。
- 抛错误之后.then 返回的是 reject 状态的 Promise,所以执行 catch,打印 2。
- 执行完.cath 整个返回的是 resolve 状态的 Promise，所以后面的`.then就不会被执行，3也不会被打印`。
- 打印结果为：`1,2`。

:::tip
这个题目主要是考察 then 和 catch 将会返回什么状态的 Promise。

- 无论是 then/catch 只要它里面没有报错，它永远返回的是 resolve 状态下的 Promise,只要有报错就会返回 reject 状态下的 Promise。
- resolve 状态下的 Promise 执行.then。reject 状态下的 Promise 执行.catch。
  :::

## 场景题- async/await 语法

```js
async function fn() {
  return 100
}
;(async function() {
  const a = fn()
  const b = await fn()
})()

// Promise {<fulfilled>: 100}
// 100
```

sync function fn() retrun 100,执行这个 fn 返回的是一个 Promise.async 执行，返回的永远是 Promise。所以 a 是一个 Promise，值是 100。
await 相当于 then,await 后面接 Promise,b 是 100。

```js
;(async function() {
  console.log('start')
  const a = await 100
  console.log('a', a)
  const b = await Promise.resolve(200)
  console.log('b', b)
  const c = await Promise.reject(300)
  console.log('c', c)
  console.log('end')
})()
// start
// a 100
// b 200
```

- 执行 start,打印“start”
- await 后面接 100 相当于直接返回 100。所以 a:100
- await Promise.resolve(200)，await 相当于 then,这里就是直接执行 Promise.then 。所以 b:200
- await Promise.reject(300)，await 相当于 then,reject 是报错，这里报错了后面就不会执行了
- 所以结果为`'start', a 100,b 200`

:::tip

- 执行 asycn 函数，返回的是 Promise。(不管里面是啥)
- await 后面接 Primose 相当于 await 是 promise 的.then
  :::

## 场景题 - promise 和 setTimeout 的顺序

```js
console.log(100)
setTimeout(() => {
  console.log(200)
})
Promise.resolve().then(() => {
  console.log(300)
})
console.log(400)

// 100
// 400
// 300
// 200
```

## 场景题- 外加 async/await 的顺序问题

```js
async function async1() {
  console.log('async1 start')
  await async2()
  // await 后面的都作为回调内容 -- 微任务
  console.log('async1 end')
}
async function async2() {
  console.log('async2')
}
console.log('script start')

// 宏任务
setTimeout(function() {
  console.log('setTimeout')
}, 0)

async1() //执行asynce1  2

// 初始化 promise 时，传入的函数会立刻被执行
new Promise(function(resolve) {
  console.log('promise1')
  resolve()
}).then(function() {
  // 微任务
  console.log('promise2')
})
console.log('script end')

// script start
// async1 start
// async2
// promise1
// script end
// async1 end
// promise2
// setTimeout
```

1. 同步代码执行完毕（event loop -call stack 别清空）
2. 执行微任务  
   微任务按照代码顺序执行

3. 执行宏任务

:::tip

- await 后面的都作为回调内容(微任务)
- 初始化 promise 时，传入的函数会立刻被执行
  :::

```js
```
